Logout
Lenigir-Srl/risto89 pull request #33
Opened 2024-04-10 09:58 UTC by San7o

Added /logout and a logout link in the profile page. Closes #31

2024-04-10 22:29 UTC, Qw3rty26 requested changes
Looking good. Just a little question about the need of importing `java.util.HashMap` inside the `Logout.java` servlet at line 7 and a few inconsistencies with the indentation inside the `web.xml`. Other than that this looks very good.

2024-04-10 22:29 UTC, Qw3rty26 commented on src/main/java/Logout.java
> +// sessione and redirecting to the login page
Little typo in line 10, typed "sessione" instead of "session"

2024-04-10 22:29 UTC, Qw3rty26 commented on src/main/java/Logout.java
> +import java.util.HashMap;
Do we really need to import `java.util.HashMap` in Logout.java servlet? (Line 7)

2024-04-10 22:29 UTC, Qw3rty26 commented on src/main/webapp/WEB-INF/web.xml
> +	    <servlet-class>HelloServlet</servlet-class>
Indentation in line 36, 41 and 46 differ from the one used in lines 51 and 56. Please choose either one (I'd suggest using indentation like the one used in line 51) and keep it the same for the rest of the code to make reading it simpler and faster.

2024-04-15 06:56 UTC, San7o commented
Fixed code

2024-04-18 12:51 UTC, Qw3rty26 approved these changes
Looks good. Typo still present in line 10 of Logout.java....Nonetheless good to go.

2024-04-18 12:51 UTC, merged