Added DB connection
Lenigir-Srl/risto89 pull request #34
Opened 2024-04-10 10:33 UTC by San7o

Added db connection an the api /TestDB. This closes #30 

Here is what you need to recreate a test environment:

Run the DB inside docker:
```bash
root@6543ebf53605:/# java -jar /opt/db-derby-10.16.1.1-bin/lib/derbyrun.jar server start&
```

Add a table with some content (for the test, the table must be called "users" and it has to have a "name" column)
```bash
root@6543ebf53605:/# java -jar /opt/db-derby-10.16.1.1-bin/lib/derbyrun.jar ij
ij> CONNECT 'jdbc:derby://localhost:1527/DemoDB;create=true';
ij> CREATE TABLE users(ID INT PRIMARY KEY, Name VARCHAR(12));
ij> INSERT INTO users VALUES(1, 'Marco'),(2, 'Enricooo');
ij> exit;
```
Now when you connect to the DB, the page should return the values inserted into users

2024-04-10 22:19 UTC, Qw3rty26 requested changes
@San7o everything looks fine, just do a little refactor and we should be good to go.

Try to put this line:

`PrintWriter out = res.getWriter();`

only once in the `TestDB.java` servlet.


Also, this servlet isn't printing a page by using the "include" method as discussed in #6. I guess printing variables, errors and such is difficult while using the "include" method. Maybe there's a workaround? If not then printing the error without "include", like you are doing here, should be fine as well.

2024-04-10 22:19 UTC, Qw3rty26 commented on src/main/java/TestDB.java
> +        PrintWriter out = res.getWriter();
This line, together with line 42 and 54 can be put once at the start of the doGET method

2024-04-15 06:41 UTC, San7o commented
The error page is still non functional, I cannot display the error in /error yet... So I'm using the writer to print the error (since  we need this api for debugging purposes).
I refactored the code, but i think the line `PrintWriter out = res.getWriter();` should be initialized right before using it. This helps with readability, since you don't need to look up at the start of the file (and for very big files, this is best practice). It also helps with maintainability: if I need to change the error display, I will only modify the code inside the catch statement without touching any other code, leaving everything logically separated.

2024-04-18 12:55 UTC, Qw3rty26 approved these changes
lgtm

2024-04-18 12:56 UTC, merged