Closes #56: Implemented the java bean for profile
Lenigir-Srl/risto89 pull request #57
Opened 2024-04-29 10:26 UTC by Qw3rty26

Closes #56, a new Java Class called `ProfileBean.java` was added inside the `/src/main/java` directory.

It implements the `java.io.Serializable` class and has everything needed to store the "name" and "password" attributes for the profile.

The constructor of the bean sets "name" and "password" to `null` by default, it is then needed to use the corrispective 
`setName(String: name)` and `setPassword(String: password)` 
methods to populate the bean.

After the Bean is successfully created and instantiated, we can then get "name" and "password" with the methods:

`String: getName()` and `String: getPassword()`

2024-04-30 06:49 UTC, San7o requested changes
Add a method, everything else looks good

2024-04-30 06:49 UTC, San7o commented on src/main/java/ProfileBean.java
> +
You should add the constructor
```java
ProfileBean(String name, String password){
    this.name = name;
    this.password = password;
}
```

2024-04-30 13:53 UTC, San7o commented on src/main/java/ProfileBean.java
> +public class ProfileBean implements Serializable {
Change `ProfileBean` to `TentativoaccessoBean`

2024-04-30 13:54 UTC, San7o commented on src/main/java/Login.java
> +	ProfileBean profile = new ProfileBean();
change `ProfileBean` to `TentativoAccessoBean`

2024-04-30 13:54 UTC, San7o requested changes
Change the name of the class

2024-05-01 11:35 UTC, San7o commented
I need this code fixes asap, I'll close the PR. This, with the fixes, ill be implemented in my next PR

2024-05-01 13:17 UTC, Qw3rty26 commented
@San7o I understand your immediate need of this Pull Request to be added to our webapp, however please note you can't just delete done work just like that, instead please be a bit more patient and wait for changes to be made.

Thank you.

2024-05-01 13:28 UTC, Qw3rty26 commented
I updated the code for the Java Bean, its name is now `TentativoAccessoBean.java` as requested.
A new constructor was also added.
Everything should be looking good now.

2024-05-01 19:29 UTC, Qw3rty26 commented
this pull request isnt needed anymore after #72 so i guess it will be sent into the trash

2024-05-01 19:29 UTC, closed without merging