Added signup page
Lenigir-Srl/risto89 pull request #74
Opened 2024-05-05 10:01 UTC by San7o

Closes #49

2024-05-05 11:05 UTC, Qw3rty26 requested changes
Wonderfull code @San7o! Before merging this PR though, i added two comments on how the variables needed for the signup are actually handled. Maybe it is my missunderstanding on how a MVC compliant webapp is made. So hit me up with a response regarding my comments and ill be sure to accept your PR if everything's ok!

2024-05-05 11:05 UTC, Qw3rty26 commented on src/main/java/Signup.java
> +        String nome = req.getParameter("nome");
Shouldn't these be made using a java bean?

2024-05-05 11:05 UTC, Qw3rty26 commented on src/main/java/Signup.java
> +        ProfiloBean profiloBean = new ProfiloBean(nome,
You cannot create String variables and then pass them to create a bean....That deletes the sole purpose of having a java bean in the first place.

2024-05-05 11:05 UTC, Qw3rty26 commented on src/main/java/Signup.java
> +        String nome = req.getParameter("nome");
By "these" i mean the "String nome", "String cognome" ecc...

2024-05-05 11:06 UTC, Qw3rty26 commented on src/main/java/Signup.java
> +        ProfiloBean profiloBean = new ProfiloBean(nome,
Or at least that's what i think?

2024-05-06 07:23 UTC, San7o commented on src/main/java/Signup.java
> +        String nome = req.getParameter("nome");
We first need to check that the parameters exist before creating the bean

2024-05-06 07:28 UTC, San7o commented
My design decision when writing this code was the following: It's wrong and memory inefficient to create a bean with missing parameters, so first I check that the parameters exist and are valid, then I create a bean. This is debatable and maybe where is a better way. From a memory prospective, this is more efficient and from a logical prospective It's wrong to create a bean with missing parameters. On the other hand, maybe checking that the user already exists could be done with the bean instead of using only the username. My choice was to be more memory efficient. We may discuss this further.

2024-05-06 15:00 UTC, Qw3rty26 commented
I can see your point @San7o. We should wait to push this PR until we can ask _that person_ what we can and cannot do ;)

2024-05-07 16:18 UTC, San7o commented
I had a vision, Vincenzo Marco spoke to me, he said this PR is fine and should be merged, glory to Vincenzo Marco 














(We didn't book an appointment with the messiah yet so we might just implement the feaure since It's prerry basic and maybe change it later)

2024-05-07 17:01 UTC, Qw3rty26 approved these changes
Very good code!!!!!

2024-05-07 17:01 UTC, merged