Ordered the webapp directory
Lenigir-Srl/risto89 pull request #79
Opened 2024-05-07 17:52 UTC by Qw3rty26

The `/webapp` directory has been ordered, creating new subdirectories, respectively called:

`/jsp` for jsp files
`/html` for html files
`/css` for css files
`/js` for javascript files

2024-05-07 20:06 UTC, San7o commented
There are many problems with this PR, basically the application is broken in every way. You should update the references of those files both on the java classes and in the html, referencing header and footer, and the various scripts. The current state of this PR is not ready for Merge, you just committed to save your work pheraps?

2024-05-09 14:38 UTC, San7o requested changes
PLEASE test your code before writing a PR

You should also change the path in Profile.java in line 41 to "/WEB-INF/jsp/Profile.jsp"

2024-05-09 14:38 UTC, San7o commented on src/main/java/Error.java
> +    req.getRequestDispatcher("./jsp/Errorpage.jsp").include(req, res);
remove the dot

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/Loginpage.jsp
> +                    <input type="email" id="email" name="email" class="form-control form-control-lg" required/>
input name here is "username" not "email"

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/Loginpage.jsp
> +                    <input type="email" id="email" name="email" class="form-control form-control-lg" required/>
Please do not commit untested code

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/Loginpage.jsp
> +                    <input type="email" id="email" name="email" class="form-control form-control-lg" required/>
Also input type is "text" not "email" since we can login via username

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/Loginpage.jsp
> +  <input class="form-check-input fs-3" type="checkbox" id="flexSwitchCheckDefault" onchange="makePasswordVisible()" autocomplete="off">
Why is this input inside the form? Remove it

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/js/Loginpage.js
> +   document.forms["loginForm"]["email"].value = "";
"username" instead of "email"

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/WEB-INF/jsp/Profile.jsp
Change header, now located in "../../jsp/Header.jsp"
same for footer

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="text" id="nome" name="nome" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="text" id="cognome" name="cognome" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="date" id="dataNascita" name="dataNascita" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="tel" id="telefono" name="telefono" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                    <input type="email" id="email" name="email" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                      <input type="text" id="username" name="username" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="getPasswordState()" id="password" name="password" class="form-control" />
set this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="getPasswordState()" id="ripetiPassword" name="ripetiPassword" class="form-control" />
change this as required

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="getPasswordState()" id="ripetiPassword" name="ripetiPassword" class="form-control" />
Use "password" instead of "usePasswordState()"

2024-05-09 14:38 UTC, San7o commented on src/main/webapp/jsp/SignupPage.jsp
> +                        <input type="getPasswordState()" id="password" name="password" class="form-control" />
What the fine is "getPasswordState()"? use "password"
Indeed, getPasswordState() does not work well with the "makePasswordvisible()" script, it has inverted values

2024-05-09 14:39 UTC, San7o commented
Upsie I noticed the branch name "Currently Working", keep it up!

2024-05-10 17:44 UTC, Tech-Matt commented
Dear Team,

I hope this message finds you well. I am writing to discuss some concerns I have about the current state of our codebase. Please understand that this is not a critique of anyone’s abilities or efforts, but rather an attempt to improve the quality of our work and the efficiency of our team.

After reviewing the code, I’ve noticed several areas that could benefit from improvement. The structure and organization of the code, in particular, seem to lack the clarity and consistency we usually strive for. It’s as if the code has been written without a clear plan or understanding of best practices. This lack of structure can make it difficult for others to understand and maintain the code, which can slow down our development process and lead to bugs and errors.

In some ways, it’s reminiscent of how a toddler might approach a complex task - with enthusiasm and creativity, but without the necessary knowledge or experience to achieve the best results. While this comparison might seem harsh, I believe it accurately reflects the current state of our codebase.

To address these issues, I suggest we take the following steps:

**Code Review:** Let’s start by conducting a thorough code review. This will help us identify specific areas that need improvement and develop a plan to address them.
**Coding Standards:** We should establish and adhere to a set of coding standards. This will ensure that our code is consistent, readable, and maintainable.
**Training:** If necessary, we could consider providing additional training or resources to help our team improve their coding skills.
Refactoring: Once we’ve identified the problem areas, we can begin refactoring the code. This will involve rewriting certain sections of the code to improve its structure and efficiency.
**Testing:** Finally, we should implement rigorous testing to ensure that our code is functioning as expected and to catch any potential issues early on.
Remember, the goal here is not to point fingers or assign blame, but to work together to improve the quality of our code and the success of our projects. I believe that with a little effort and collaboration, we can turn this situation around and create a codebase that we can all be proud of.

Thank you for taking the time to read this message. I look forward to discussing these issues further and working together to improve our codebase.

Best regards, TechMatt

2024-05-10 17:49 UTC, Tech-Matt commented
I am stepping down as leader of this estabilishment, 
I hope you grow as coders,
Best Regards,

Darth Vader 0_0

2024-05-10 18:19 UTC, Qw3rty26 commented
> Dear Team,
> 
> I hope this message finds you well. I am writing to discuss some concerns I have about the current state of our codebase. Please understand that this is not a critique of anyone’s abilities or efforts, but rather an attempt to improve the quality of our work and the efficiency of our team.
> 
> After reviewing the code, I’ve noticed several areas that could benefit from improvement. The structure and organization of the code, in particular, seem to lack the clarity and consistency we usually strive for. It’s as if the code has been written without a clear plan or understanding of best practices. This lack of structure can make it difficult for others to understand and maintain the code, which can slow down our development process and lead to bugs and errors.
> 
> In some ways, it’s reminiscent of how a toddler might approach a complex task - with enthusiasm and creativity, but without the necessary knowledge or experience to achieve the best results. While this comparison might seem harsh, I believe it accurately reflects the current state of our codebase.
> 
> To address these issues, I suggest we take the following steps:
> 
> **Code Review:** Let’s start by conducting a thorough code review. This will help us identify specific areas that need improvement and develop a plan to address them. **Coding Standards:** We should establish and adhere to a set of coding standards. This will ensure that our code is consistent, readable, and maintainable. **Training:** If necessary, we could consider providing additional training or resources to help our team improve their coding skills. Refactoring: Once we’ve identified the problem areas, we can begin refactoring the code. This will involve rewriting certain sections of the code to improve its structure and efficiency. **Testing:** Finally, we should implement rigorous testing to ensure that our code is functioning as expected and to catch any potential issues early on. Remember, the goal here is not to point fingers or assign blame, but to work together to improve the quality of our code and the success of our projects. I believe that with a little effort and collaboration, we can turn this situation around and create a codebase that we can all be proud of.
> 
> Thank you for taking the time to read this message. I look forward to discussing these issues further and working together to improve our codebase.
> 
> Best regards, TechMatt

??????

2024-05-10 18:47 UTC, San7o commented
> Dear Team,
> 
> I hope this message finds you well. I am writing to discuss some concerns I have about the current state of our codebase. Please understand that this is not a critique of anyone’s abilities or efforts, but rather an attempt to improve the quality of our work and the efficiency of our team.
> 
> After reviewing the code, I’ve noticed several areas that could benefit from improvement. The structure and organization of the code, in particular, seem to lack the clarity and consistency we usually strive for. It’s as if the code has been written without a clear plan or understanding of best practices. This lack of structure can make it difficult for others to understand and maintain the code, which can slow down our development process and lead to bugs and errors.
> 
> In some ways, it’s reminiscent of how a toddler might approach a complex task - with enthusiasm and creativity, but without the necessary knowledge or experience to achieve the best results. While this comparison might seem harsh, I believe it accurately reflects the current state of our codebase.
> 
> To address these issues, I suggest we take the following steps:
> 
> **Code Review:** Let’s start by conducting a thorough code review. This will help us identify specific areas that need improvement and develop a plan to address them. **Coding Standards:** We should establish and adhere to a set of coding standards. This will ensure that our code is consistent, readable, and maintainable. **Training:** If necessary, we could consider providing additional training or resources to help our team improve their coding skills. Refactoring: Once we’ve identified the problem areas, we can begin refactoring the code. This will involve rewriting certain sections of the code to improve its structure and efficiency. **Testing:** Finally, we should implement rigorous testing to ensure that our code is functioning as expected and to catch any potential issues early on. Remember, the goal here is not to point fingers or assign blame, but to work together to improve the quality of our code and the success of our projects. I believe that with a little effort and collaboration, we can turn this situation around and create a codebase that we can all be proud of.
> 
> Thank you for taking the time to read this message. I look forward to discussing these issues further and working together to improve our codebase.
> 
> Best regards, TechMatt

Subject: Re: Re: Concerns Regarding Code Quality

Dear TechMatt,

I hope this message finds you well, albeit slightly singed from the scathing inferno of your prose. Permit me to illuminate the myriad ways in which your communication has missed the mark, akin to a blindfolded archer aiming for the moon.

Firstly, let's address the tone. Your verbose and flowery language does little to conceal the underlying condescension dripping from every word. Comparing our codebase to the scribbles of a toddler with crayons? Such a metaphor does nothing to foster constructive dialogue; instead, it belittles the efforts of your colleagues and undermines morale.

Moreover, your insistence on grandiloquent imagery only serves to obfuscate the true issues at hand. Rather than engaging in theatrical rhetoric, why not communicate plainly and directly? Clarity, after all, is the cornerstone of effective communication.

Next, let's dissect the substance—or lack thereof—of your proposed solutions. Conducting a code review? Establishing coding standards? Refactoring? These are not revolutionary ideas; they are basic tenets of software development that any competent team should already be employing. Your belabored exposition of these elementary concepts only serves to highlight your own lack of understanding or, worse yet, your assumption of the team's incompetence.

Furthermore, your suggestion of providing additional training comes across as patronizing. Are you implying that your colleagues are not capable of fulfilling their roles without hand-holding? Such insinuations are not only insulting but also indicative of a lack of respect for your peers' capabilities.

In summary, your missive reads less like a sincere attempt to address concerns and more like a self-indulgent exercise in pomposity. If you truly wish to contribute to the improvement of our codebase, I suggest adopting a more humble and collaborative approach—one that respects the contributions of your fellow team members and focuses on tangible solutions rather than theatrical grandstanding.

Regards,

[Your Name]

2024-05-12 09:26 UTC, merged